[workspace]
members = [
    "crates/*",
]

# The profile used for `cargo build`.
[profile.dev]
panic = "abort" # disable stack unwinding on panic

# The profile used for `cargo build --release`.
[profile.release]
panic = "abort" # disable stack unwinding on panic

[workspace.package]
authors = [
    "Yuuki Rika <yvvki@duck.com>",
]
edition = "2021"
description = "Hybrid and modular POSIX"
repository = "https://github.com/yvvki/blue-kernel"
license = "MIT OR Apache-2.0"
