[package]
name = "blue-kernel"
version = "0.1.0"
authors = ["Yuuki Rika <yvvki@duck.com>"]
edition = "2021"
description = "POSIX hybrid kernel"
repository = "https://github.com/yvvki/blue-kernel"
license = "MIT OR Apache-2.0"

[dependencies]
